### ISSUE TITLE
The xcodeproj is changed every time generate with Xcode 10.

### ISSUE THREAD

**Issue by yutailang0119** [ishkawa/DIKit#58] opened 2018-09-16 17:07 UTC
I'm trying to support Xcode 10.
However, the generated xcodeproj is changed every time when I execute `swift package generate-xcodeproj` .

Swift Package Manager is not yet suitable for iOS.
I think that it is necessary to replace the generate of xcodeproj file with another tool.
I would like to consider migration from Swift Package Manager.

**Comment by ishkawa** [comment] 2018-10-29 17:44
Yes, using xcodeproj generated by SwiftPM is a bit hard. Actually we encountered several issues caused by it so far, and dealt with them. Since it is not so important to continue to use SwiftPM xcodeproj, I decided to use xcodeproj created by Xcode, and keep project SwiftPM compatible.

To do that, I will send following pull requests:

1. Drop Stencil from dependencies because it doesn't have xcodeproj.
2. Reorganize project to manage settings by Xcode and Carthage.

**Comment by yutailang0119** [comment] 2018-10-30 07:58
I agree with you about that unimportant to use SwiftPM.

@norio-nomura san considered management by Carthage + git submodule.
I think this is also good.
https://github.com/ishkawa/DIKit/compare/master...norio-nomura:update-xcodeproj

* Submodule is managed by Carthage.
* Rewrite the .build/checkouts/* in project.pbxproj generated by `generate-xcodeproj` to Carthage/Checkouts/* .
* Deleted modulemap which became unnecessary in Swift 4.2.

**Comment by ishkawa** [comment] 2018-10-31 13:37
Thank you for the useful information!

**Comment by ishkawa** [comment] 2018-11-01 15:52
I think this is resolved by #60.

**Closed as completed by ishkawa** 2018-11-01 15:52 UTC
